In [1]:
"""
Simple exercises to get used to TensorFlow API
You should thoroughly test your code.
TensorFlow's official documentation should be your best friend here
CS20: "TensorFlow for Deep Learning Research"
cs20.stanford.edu
Created by Chip Huyen (chiphuyen@cs.stanford.edu)
"""
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'

import tensorflow as tf

In [2]:
gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.8)
sessConfig=tf.ConfigProto(gpu_options=gpu_options)

In [3]:
sess = tf.InteractiveSession( config = sessConfig )

In [13]:
tf.set_random_seed( 39 )
tfBoard = tf.summary.FileWriter( "./graphs/q1", sess.graph )

In [4]:
###############################################################################
# 1a: Create two random 0-d tensors x and y of any distribution.
# Create a TensorFlow object that returns x + y if x > y, and x - y otherwise.
# Hint: look up tf.cond()
# I do the first problem for you
###############################################################################

x = tf.random_uniform([])  # Empty array as shape creates a scalar.
y = tf.random_uniform([])
out = tf.cond(tf.greater(x, y), lambda: x + y, lambda: x - y)
print(sess.run(out))

0.53118443


In [23]:
###############################################################################
# 1b: Create two 0-d tensors x and y randomly selected from the range [-1, 1).
# Return x + y if x < y, x - y if x > y, 0 otherwise.
# Hint: Look up tf.case().
###############################################################################
x = tf.random_uniform( [], minval = -1, maxval = 1 )
y = tf.random_uniform( [], minval = -1, maxval = 1 )

out = tf.cond( 
    tf.less( x, y ), 
    lambda: x + y, 
    lambda: tf.cond( tf.greater( x, y ), 
                    lambda: x - y, 
                    lambda: 0. 
                   ) 
)
print( sess.run( [out] ) )


[0.720206]


In [28]:
###############################################################################
# 1c: Create the tensor x of the value [[0, -2, -1], [0, 1, 2]] 
# and y as a tensor of zeros with the same shape as x.
# Return a boolean tensor that yields Trues if x equals y element-wise.
# Hint: Look up tf.equal().
###############################################################################

x = tf.constant( [[0, -2, -1], [0, 1, 2]]  )
y = tf.zeros_like( x )
out = tf.equal( x, y )

print( sess.run( out ) )

[[ True False False]
 [ True False False]]


In [46]:
###############################################################################
# 1d: Create the tensor x of value 
# [29.05088806,  27.61298943,  31.19073486,  29.35532951,
#  30.97266006,  26.67541885,  38.08450317,  20.74983215,
#  34.94445419,  34.45999146,  29.06485367,  36.01657104,
#  27.88236427,  20.56035233,  30.20379066,  29.51215172,
#  33.71149445,  28.59134293,  36.05556488,  28.66994858].
# Get the indices of elements in x whose values are greater than 30.
# Hint: Use tf.where().
# Then extract elements whose values are greater than 30.
# Hint: Use tf.gather().
###############################################################################

x = tf.constant( [29.05088806,  27.61298943,  31.19073486,  29.35532951,
                  30.97266006,  26.67541885,  38.08450317,  20.74983215,
                  34.94445419,  34.45999146,  29.06485367,  36.01657104,
                  27.88236427,  20.56035233,  30.20379066,  29.51215172,
                  33.71149445,  28.59134293,  36.05556488,  28.66994858]
               )

mask = tf.fill( tf.shape(x), True )
trueIndicesWhere = tf.reshape( tf.where( tf.greater( x, 30 ) ), [-1] )

trueIndices = sess.run( trueIndicesWhere )
print( trueIndices )

filteredVals = tf.gather( x, trueIndices )
print( sess.run( filteredVals ) )

[ 2  4  6  8  9 11 14 16 18]
[31.190735 30.97266  38.084503 34.944454 34.45999  36.01657  30.20379
 33.711494 36.055565]


In [49]:
###############################################################################
# 1e: Create a diagnoal 2-d tensor of size 6 x 6 with the diagonal values of 1,
# 2, ..., 6
# Hint: Use tf.range() and tf.diag().
###############################################################################
seq = tf.range(1,7)
diag = tf.diag( seq )
print( sess.run( diag ) )

[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


In [52]:
###############################################################################
# 1f: Create a random 2-d tensor of size 10 x 10 from any distribution.
# Calculate its determinant.
# Hint: Look at tf.matrix_determinant().
###############################################################################

tensor = tf.random.normal( [10, 10], seed = 39 )
det = tf.matrix_determinant( tensor )
print( sess.run( det ) )
print( sess.run( tensor ) )

-316.61505
[[-0.08584421  1.2286414  -2.3233972  -1.2203773  -0.43624303  0.7975135
   0.29657778  1.2836806   0.9893475  -1.4594897 ]
 [ 1.7537892  -0.98934394  1.213877    0.07860077  1.2145444  -0.04078407
  -1.1706752  -0.45150048  1.0927207   0.01912704]
 [ 0.5455254  -0.9176182   1.6131482  -0.07915685 -0.32051048  0.5278167
  -0.02602592  0.48626202  0.7072311   1.8109593 ]
 [-0.76975125  0.87817425  0.37341434  1.1017609  -0.19898602  0.3335209
   0.55055314  0.10963187 -1.2421621   2.2010536 ]
 [-0.68277234 -0.6221651  -0.9112568  -0.08237689 -0.04760491  0.37429696
   0.30789924  0.71601343  0.16277264  0.71686053]
 [-0.06605926  0.6080401  -0.94159746 -0.8275424   0.72466177  1.6645539
  -0.04569227  1.1780572   0.20640792 -1.5270218 ]
 [ 1.2304268   1.0017675   0.9833425  -0.31209537  2.0907457   1.3893663
   0.9535505   0.73348373  1.5933542  -1.1357813 ]
 [ 0.23827754 -0.40438646 -0.14850315 -1.3621339  -0.8101369   0.92316544
   1.198467    0.07190312 -0.43746406 -0.5261

In [54]:
###############################################################################
# 1g: Create tensor x with value [5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9].
# Return the unique elements in x
# Hint: use tf.unique(). Keep in mind that tf.unique() returns a tuple.
###############################################################################

x = tf.constant( [5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9] )
uniqTuples = tf.unique( x )
uniq = uniqTuples.y
print( sess.run( uniq ) )

[ 5  2  3 10  6  4  1  0  9]


In [ ]:

###############################################################################
# 1h: Create two tensors x and y of shape 300 from any normal distribution,
# as long as they are from the same distribution.
# Use tf.cond() to return:
# - The mean squared error of (x - y) if the average of all elements in (x - y)
#   is negative, or
# - The sum of absolute value of all elements in the tensor (x - y) otherwise.
# Hint: see the Huber loss function in the lecture slides 3.
###############################################################################

x = tf.random.uniform( minval= -100, maxval= 100, seed=39 )
y = tf.random.uniform( minval= -100, maxval= 100, seed=40 )

true_fn = lambda avg: 
